import { app, safeStorage } from 'electron';
import { existsSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';

const KEY_FILE = 'ledger-client-key.json';
const MAX_PREVIOUS_KEYS = 5;

export type E2eKeyRing = {
  primary: string;
  previous: string[];
  updatedAt: number;
};

// On-disk wrapper. `data` is safeStorage ciphertext (hex) when enc=true, or the raw
// keyring JSON when enc=false (a host with no OS keyring). Legacy installs stored the
// bare keyring JSON with no wrapper — readStored() still accepts that and migrates it.
type StoredKeyRing = { enc: boolean; data: string };

// Thrown when a key file EXISTS but cannot be read back (failed safeStorage decrypt or
// corrupt content). We deliberately refuse to mint a fresh key in that case: doing so
// would silently orphan every ledger row encrypted under the unreadable key. Surfacing
// loudly lets an admin re-import the correct key (e2e:keys:export/import) instead.
export class KeyRingUnreadableError extends Error {}

function keyPath() {
  return join(app.getPath('userData'), KEY_FILE);
}

function safeJsonParse(raw: string): unknown {
  try {
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

function parseKeyRing(raw: string | null): E2eKeyRing | null {
  if (!raw) return null;
  const parsed = safeJsonParse(raw) as (Partial<E2eKeyRing> & { keyBase64?: string }) | null;
  if (!parsed || typeof parsed !== 'object') return null;
  if (parsed.primary) {
    return {
      primary: String(parsed.primary),
      previous: Array.isArray(parsed.previous) ? parsed.previous.map(String) : [],
      updatedAt: Number(parsed.updatedAt ?? Date.now()),
    };
  }
  if (parsed.keyBase64) {
    return {
      primary: String(parsed.keyBase64),
      previous: [],
      updatedAt: Number(parsed.updatedAt ?? Date.now()),
    };
  }
  return null;
}

function writeStored(ring: E2eKeyRing) {
  const json = JSON.stringify(ring);
  let stored: StoredKeyRing;
  if (safeStorage.isEncryptionAvailable()) {
    stored = { enc: true, data: safeStorage.encryptString(json).toString('hex') };
  } else {
    // No OS keyring: keep plaintext. The E2E key must NEVER be lost — unlike an auth
    // token it cannot be regenerated by re-login, and losing it makes the encrypted
    // ledger undecryptable. At-rest encryption is therefore best-effort: it applies
    // wherever safeStorage is available (Windows/macOS prod clients), and falls back
    // to plaintext only where the OS offers no keyring at all.
    stored = { enc: false, data: json };
  }
  // Atomic write: a crash/power-loss mid-write must never truncate the sole on-disk
  // copy of the key (a truncated file would be unreadable → loud refusal). Write to a
  // temp file, then rename over the target.
  const target = keyPath();
  const tmp = `${target}.tmp`;
  writeFileSync(tmp, JSON.stringify(stored, null, 2));
  renameSync(tmp, target);
}

// Returns the keyring (with a `migrated` flag for plaintext/legacy files that should be
// re-encrypted), null when no file exists yet, or throws KeyRingUnreadableError.
function readStored(): { ring: E2eKeyRing; migrated: boolean } | null {
  if (!existsSync(keyPath())) return null;
  const raw = readFileSync(keyPath(), 'utf8');
  const obj = safeJsonParse(raw);

  // New wrapper format { enc, data }.
  if (obj && typeof obj === 'object' && typeof (obj as StoredKeyRing).data === 'string' && typeof (obj as StoredKeyRing).enc === 'boolean') {
    const stored = obj as StoredKeyRing;
    if (stored.enc) {
      let json: string;
      try {
        json = safeStorage.decryptString(Buffer.from(stored.data, 'hex'));
      } catch (e) {
        throw new KeyRingUnreadableError(`ledger E2E key present but undecryptable via safeStorage: ${String(e)}`);
      }
      const ring = parseKeyRing(json);
      if (!ring) throw new KeyRingUnreadableError('ledger E2E key decrypted but unparseable');
      return { ring, migrated: false };
    }
    const ring = parseKeyRing(stored.data);
    if (!ring) throw new KeyRingUnreadableError('ledger E2E key (plaintext wrapper) unparseable');
    return { ring, migrated: true };
  }

  // Legacy bare-keyring JSON (pre-safeStorage) — valid, flag for migration to encrypted.
  const legacy = parseKeyRing(raw);
  if (legacy) return { ring: legacy, migrated: true };

  // File exists but is neither a wrapper nor a parseable keyring → refuse to rotate.
  throw new KeyRingUnreadableError('ledger E2E key file exists but is unreadable');
}

export function loadOrCreateKeyRing(): E2eKeyRing {
  const read = readStored(); // may throw KeyRingUnreadableError — caller surfaces it
  if (read) {
    // Re-write only when it actually UPGRADES the at-rest form: a plaintext/legacy file
    // on a host WITH safeStorage becomes encrypted. On a keyring-less host an enc:false
    // file is already in its final form, so re-writing every load would be pure write
    // amplification on the only copy of the key — skip it.
    if (read.migrated && safeStorage.isEncryptionAvailable()) {
      try {
        writeStored(read.ring);
      } catch {
        // Keep using the in-memory ring even if the re-encrypt write fails.
      }
    }
    return read.ring;
  }
  const primary = randomBytes(32).toString('base64');
  const ring: E2eKeyRing = { primary, previous: [], updatedAt: Date.now() };
  writeStored(ring);
  return ring;
}

export function getKeyRing(): E2eKeyRing {
  return loadOrCreateKeyRing();
}

export function rotateKey(): E2eKeyRing {
  const ring = loadOrCreateKeyRing();
  const nextPrimary = randomBytes(32).toString('base64');
  const previous = [ring.primary, ...ring.previous].slice(0, MAX_PREVIOUS_KEYS);
  const next: E2eKeyRing = { primary: nextPrimary, previous, updatedAt: Date.now() };
  writeStored(next);
  return next;
}

export function exportKeyRing(): E2eKeyRing {
  return loadOrCreateKeyRing();
}

export function keyRingToBuffers(ring: E2eKeyRing): Buffer[] {
  const all = [ring.primary, ...ring.previous];
  return all.map((k) => Buffer.from(k, 'base64')).filter((buf) => buf.length > 0);
}
