-- Реплика карточек двигателей (план engine-cards-strict-2026-10, E3a).
-- Nullability — ровно как серверная erp_engine_cards (миграция 0105), иначе
-- checkReplicaStrictness уронит pull. Флаги — integer NOT NULL DEFAULT 0.
-- Тот же DDL продублирован в `ensureClientSchemaParity` (migrate.ts) и в android-миграторе.

CREATE TABLE `erp_engine_cards` (
	`id` text PRIMARY KEY NOT NULL,
	`engine_number` text,
	`engine_internal_number` text,
	`engine_internal_number_year` integer,
	`engine_brand_id` text,
	`engine_brand` text,
	`arrival_date` integer,
	`customer_id` text,
	`contract_id` text,
	`contract_section_number` text,
	`workshop_id` text,
	`status_rework_sent` integer NOT NULL DEFAULT 0,
	`status_rework_sent_date` integer,
	`status_scrap_confirmed` integer NOT NULL DEFAULT 0,
	`status_scrap_confirmed_date` integer,
	`status_repair_started` integer NOT NULL DEFAULT 0,
	`status_repair_started_date` integer,
	`status_repaired` integer NOT NULL DEFAULT 0,
	`status_repaired_date` integer,
	`status_customer_sent` integer NOT NULL DEFAULT 0,
	`status_customer_sent_date` integer,
	`status_customer_accepted` integer NOT NULL DEFAULT 0,
	`status_customer_accepted_date` integer,
	`status_storage_received` integer NOT NULL DEFAULT 0,
	`status_storage_received_date` integer,
	`status_rejected` integer NOT NULL DEFAULT 0,
	`status_rejected_date` integer,
	`scrap_reason` text,
	`reclamation_flag` integer NOT NULL DEFAULT 0,
	`reclamation_accepted_date` integer,
	`reclamation_customer_reason` text,
	`reclamation_actual_defect` text,
	`reclamation_defect_nature` text,
	`reclamation_act_number` text,
	`reclamation_verdict_date` integer,
	`reclamation_shipped_date` integer,
	`reclamation_comment` text,
	`reclamation_verdict` text,
	`reclamation_repair_status` text,
	`repeat_arrival_flag` integer NOT NULL DEFAULT 0,
	`number_collision_flag` integer NOT NULL DEFAULT 0,
	`previous_arrival_id` text,
	`merged_into` text,
	`arrival_invoice` text,
	`shipment_invoice` text,
	`engine_note` text,
	`docs_state` text,
	`docs_aspvr_contractor_date` integer,
	`docs_vp_sent_date` integer,
	`docs_vp_returned_date` integer,
	`docs_aspvr_customer_scan_date` integer,
	`docs_aspvr_customer_original_date` integer,
	`docs_track_or_act` text,
	`docs_aspvr_signed_customer_date` integer,
	`docs_aspvr_customer_received` integer NOT NULL DEFAULT 0,
	`docs_return_scan_date` integer,
	`docs_return_original_date` integer,
	`docs_note` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`last_server_seq` integer,
	`deleted_at` integer,
	`sync_status` text DEFAULT 'synced' NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `erp_engine_cards_number_idx` ON `erp_engine_cards` (`engine_number`);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `erp_engine_cards_contract_idx` ON `erp_engine_cards` (`contract_id`);
