# Idempotently writes backend-api/.env.dev and electron-app/.env.dev for the
# local verifier-electron stack.
#
# PG password is taken from $env:PGPASSWORD; if unset, the field stays empty
# and backend falls back to %APPDATA%\postgresql\pgpass.conf.

. (Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) '_common.ps1')

Test-PgConnectivity
$repo = Get-RepoRoot
$pg = Get-PgConfig
$pgPassword = if ($env:PGPASSWORD) { $env:PGPASSWORD } else { '' }

$backendEnvPath  = Join-Path $repo 'backend-api\.env.dev'
$electronEnvPath = Join-Path $repo 'electron-app\.env.dev'

function Get-OrGenerate {
    param(
        [string]$Path,
        [string]$Key,
        [scriptblock]$Generator
    )
    if (Test-Path $Path) {
        $existing = Select-String -Path $Path -Pattern "^$Key=" -SimpleMatch:$false -ErrorAction SilentlyContinue
        if ($existing) {
            $value = ($existing[0].Line -split '=', 2)[1]
            if ($value) { return $value }
        }
    }
    return (& $Generator)
}

$jwtSecret = Get-OrGenerate -Path $backendEnvPath -Key 'MATRICA_JWT_SECRET' -Generator { New-RandomHex 32 }
$ledgerKey = Get-OrGenerate -Path $backendEnvPath -Key 'MATRICA_LEDGER_DATA_KEY' -Generator { New-RandomBase64 32 }

$backendEnv = @"
# Generated by verifier-electron setup-env.ps1 - do not edit manually.
PGHOST=$($pg.Host)
PGPORT=$($pg.Port)
PGDATABASE=$($pg.Database)
PGUSER=$($pg.User)
PGPASSWORD=$pgPassword
PGSSL=false

HOST=127.0.0.1
PORT=3001
TZ=Europe/Moscow
MATRICA_INSTANCE_ROLE=primary

MATRICA_JWT_SECRET=$jwtSecret
MATRICA_LEDGER_DATA_KEY=$ledgerKey

MATRICA_LOGS_DIR=backend-api/logs
MATRICA_UPLOADS_DIR=backend-api/uploads
MATRICA_UPDATES_DIR=backend-api/updates
MATRICA_LEDGER_DIR=backend-api/ledger

MATRICA_API_URL=http://127.0.0.1:3001
MATRICA_PUBLIC_BASE_URL=http://127.0.0.1:3001
SYNC_V2_ENFORCE=1
MATRICA_SYNC_AUTOHEAL_ENABLED=0
MATRICA_SYNC_PULL_ADAPTIVE_ENABLED=0

MATRICA_TORRENT_TRACKER_PORT=6969
MATRICA_TORRENT_TRACKER_URLS=http://127.0.0.1:6969/announce

AI_PROFILE=balanced
AI_REPORT_ENABLED=false
AI_ENABLED=false
AI_CHAT_TOOLS_ENABLED=false
AI_ANALYTICS_TOOLS_ENABLED=false
AI_LOG_ANALYSIS_ENABLED=false
"@

$electronEnv = @"
# Generated by verifier-electron setup-env.ps1.
MATRICA_API_URL=http://127.0.0.1:3001
MATRICA_SYNC_V2=1
MATRICA_UPDATE_PEER_HTTP_PORT=3001
MATRICA_UPDATE_LAN_ENABLED=0
"@

$backendEnv  | Out-File -FilePath $backendEnvPath  -Encoding utf8 -NoNewline -Force
$electronEnv | Out-File -FilePath $electronEnvPath -Encoding utf8 -NoNewline -Force

Write-Output "[setup-env] backend  -> $backendEnvPath"
Write-Output "[setup-env] electron -> $electronEnvPath"
Write-Output "[setup-env] PG: $($pg.User)@$($pg.Host):$($pg.Port)/$($pg.Database)"
